### ISSUE TITLE
Unexpected console statement.

### ISSUE THREAD

**Issue by margittennosaar** [oniso20/taste-it#3]
https://github.com/oniso20/taste-it/blob/a58fe92ebe1045027203eecca83839acd360b17a/src/hooks/useFetch.js#L37

In JavaScript that is designed to be executed in the browser, it's considered a best practice to avoid using methods on console. Such messages are considered to be for debugging purposes and therefore not suitable to ship to the client. In general, calls using console should be stripped before being pushed to production.

**Comment by oniso20** [comment]
Thanks for the feedback. The `console.log` has been removed, although it was added as a guide for debugging. Nevertheless, the disadvantages of using it outweigh the benefits. Thanks.
