### ISSUE TITLE
'data' is already declared in the upper scope on line 4 

### ISSUE THREAD

**Issue by margittennosaar** [oniso20/taste-it#5]
https://github.com/oniso20/taste-it/blob/a58fe92ebe1045027203eecca83839acd360b17a/src/hooks/useFetch.js#L30

This can cause confusion while reading the code and it's impossible to access the global variable.

**Comment by oniso20** [comment]
My apologies for the confusion; the resulting data from the fetch has been renamed to `fetchedData`.
